// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu.GetCommandString(System.IntPtr,MiniShellFramework.ComTypes.GetCommandStringOptions,System.Int32,System.IntPtr,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu.InvokeCommand(MiniShellFramework.ComTypes.InvokeCommandInfo&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu.QueryContextMenu(System.IntPtr,System.UInt32,System.UInt32,System.UInt32,MiniShellFramework.ComTypes.QueryContextMenuOptions)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu2.GetCommandString(System.IntPtr,MiniShellFramework.ComTypes.GetCommandStringOptions,System.Int32,System.IntPtr,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu2.HandleMenuMsg(System.UInt32,System.IntPtr,System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu2.InvokeCommand(MiniShellFramework.ComTypes.InvokeCommandInfo&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu2.QueryContextMenu(System.IntPtr,System.UInt32,System.UInt32,System.UInt32,MiniShellFramework.ComTypes.QueryContextMenuOptions)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu3.GetCommandString(System.IntPtr,MiniShellFramework.ComTypes.GetCommandStringOptions,System.Int32,System.IntPtr,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu3.HandleMenuMsg(System.UInt32,System.IntPtr,System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu3.HandleMenuMsg2(System.UInt32,System.IntPtr,System.IntPtr,System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu3.InvokeCommand(MiniShellFramework.ComTypes.InvokeCommandInfo&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ContextMenuBase.#MiniShellFramework.ComTypes.IContextMenu3.QueryContextMenu(System.IntPtr,System.UInt32,System.UInt32,System.UInt32,MiniShellFramework.ComTypes.QueryContextMenuOptions)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.FolderCopyHookBase.#MiniShellFramework.ComTypes.ICopyHook.CopyCallback(System.IntPtr,MiniShellFramework.ComTypes.FileOperation,System.UInt32,System.String,System.UInt32,System.String,System.UInt32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#MiniShellFramework.ComTypes.IInitializeWithStream.Initialize(System.Runtime.InteropServices.ComTypes.IStream,MiniShellFramework.ComTypes.StorageModes)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#MiniShellFramework.ComTypes.IQueryInfo.GetInfoFlags(MiniShellFramework.ComTypes.InfoTipOptions&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#MiniShellFramework.ComTypes.IQueryInfo.GetInfoTip(MiniShellFramework.ComTypes.InfoTipOptions,System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#System.Runtime.InteropServices.ComTypes.IPersistFile.GetClassID(System.Guid&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#System.Runtime.InteropServices.ComTypes.IPersistFile.GetCurFile(System.String&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#System.Runtime.InteropServices.ComTypes.IPersistFile.IsDirty()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#System.Runtime.InteropServices.ComTypes.IPersistFile.Load(System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#System.Runtime.InteropServices.ComTypes.IPersistFile.Save(System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.InfoTipBase.#System.Runtime.InteropServices.ComTypes.IPersistFile.SaveCompleted(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ShellExtensionInit.#MiniShellFramework.ComTypes.IShellExtInit.Initialize(System.IntPtr,System.Runtime.InteropServices.ComTypes.IDataObject,System.UInt32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ShellPropertySheetBase.#MiniShellFramework.ComTypes.IShellPropSheetExt.AddPages(MiniShellFramework.ComTypes.AddPropertySheetPage,System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MiniShellFramework.ShellPropertySheetBase.#MiniShellFramework.ComTypes.IShellPropSheetExt.ReplacePage(System.UInt32,System.IntPtr,System.IntPtr)")]
